// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbschema

import (
	"database/sql"
)

type Blog struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
